/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Entidades.Ficha;
import javax.swing.JLabel;

/**
 *
 * @author Andres Araya
 */
public class VistaFicha extends javax.swing.JPanel {

    private Ficha ficha;

    public VistaFicha(Ficha ficha) {
        this.ficha = ficha;
        initComponents();
    }

    public Ficha getFicha() {
        return ficha;
    }

    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

    public JLabel getJlabelImagen() {
        return jlabelImagen;
    }

    public void setJlabelImagen(JLabel jlabelImagen) {
        this.jlabelImagen = jlabelImagen;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelImagen = new javax.swing.JLabel();

        jlabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/" + ficha.getTipoFicha() + ficha.getTipoJugador() + ficha.getColor() + ".png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabelImagen;
    // End of variables declaration//GEN-END:variables
}
