package Vista;

import Entidades.Ficha;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author Andres Araya
 */
public class VistaFicha extends javax.swing.JPanel {

    private Ficha ficha;

    // Colores de las casillas del tablero
    private static final Color COLOR_CASILLA_CLARA = new Color(240, 217, 181);
    private static final Color COLOR_CASILLA_OSCURA = new Color(181, 136, 99);

    // Colores de resaltado
    private static final Color COLOR_SELECCIONADA   = new Color(255, 255, 0, 140);   // amarillo
    private static final Color COLOR_MOVIMIENTO     = new Color(0, 200, 80, 180);    // verde para casilla vacía
    private static final Color COLOR_CAPTURA        = new Color(220, 40, 40, 140);   // rojo para captura

    public VistaFicha(Ficha ficha) {
        this.ficha = ficha;
        initComponents();
        setOpaque(true);
        actualizarColorBase();
    }

    public Ficha getFicha() {
        return ficha;
    }

    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

    public JLabel getJlabelImagen() {
        return jlabelImagen;
    }

    public void setJlabelImagen(JLabel jlabelImagen) {
        this.jlabelImagen = jlabelImagen;
    }

    /** Pinta el color base de la casilla (claro u oscuro del tablero). */
    private void actualizarColorBase() {
        setBackground(ficha.getColor() == 0 ? COLOR_CASILLA_CLARA : COLOR_CASILLA_OSCURA);
    }

    /**
     * Override de paint() para dibujar el overlay de resaltado DESPUÉS de
     * que los hijos (la imagen de la pieza) ya han sido pintados.
     * Esto garantiza que el overlay quede encima de la imagen.
     */
    @Override
    public void paint(Graphics g) {
        super.paint(g);  // pinta fondo, imagen y demás hijos

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        if (ficha.getFichaMarcada()) {
            // Pieza seleccionada: halo amarillo
            g2.setColor(COLOR_SELECCIONADA);
            g2.fillRect(0, 0, getWidth(), getHeight());

        } else if (ficha.getPuedeSerComida()) {
            if (ficha.getTipoFicha() == 0) {
                // Casilla vacía: círculo verde centrado
                g2.setColor(COLOR_MOVIMIENTO);
                int tam = Math.min(getWidth(), getHeight()) / 3;
                g2.fillOval(getWidth() / 2 - tam / 2, getHeight() / 2 - tam / 2, tam, tam);
            } else {
                // Pieza enemiga capturable: halo rojo con borde resaltado
                g2.setColor(COLOR_CAPTURA);
                g2.fillRect(0, 0, getWidth(), getHeight());
                g2.setColor(new Color(200, 0, 0, 220));
                g2.setStroke(new java.awt.BasicStroke(3));
                g2.drawRect(1, 1, getWidth() - 3, getHeight() - 3);
            }
        }
        g2.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelImagen = new javax.swing.JLabel();

        jlabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/" + ficha.getTipoFicha() + ficha.getTipoJugador() + ficha.getColor() + ".png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabelImagen;
    // End of variables declaration//GEN-END:variables
}
