/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Logica.Ajedrez;
import Logica.Sockets;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Araya
 */
public class VistaAreaJuego extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form VistaAreaJuego
     */
    private Ajedrez ajedrez;
    private VistaFicha matrizGrafica[][];
    private Sockets sock;

    public VistaAreaJuego() {
        this.ajedrez = new Ajedrez(8, 8);
        this.matrizGrafica = new VistaFicha[8][8];
        initComponents();
        setTitle("AJEDREZ");
        setLocationRelativeTo(null);
        agregar();
    }

    public Ajedrez getAjedrez() {
        return ajedrez;
    }

    public void setAjedrez(Ajedrez ajedrez) {
        this.ajedrez = ajedrez;
    }

    public VistaFicha[][] getMatrizGrafica() {
        return matrizGrafica;
    }

    public void setMatrizGrafica(VistaFicha[][] matrizGrafica) {
        this.matrizGrafica = matrizGrafica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnServidor = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelAreaJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));

        btnServidor.setText("Jugador 1");
        btnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServidorActionPerformed(evt);
            }
        });

        btnCliente.setText("Jugador 2");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        panelAreaJuego.setBackground(new java.awt.Color(204, 204, 204));
        panelAreaJuego.setLayout(new java.awt.GridLayout(ajedrez.getColumnas(), ajedrez.getFilas(), 1, 1));
        jScrollPane1.setViewportView(panelAreaJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        System.out.println("SOLICITUD DE LA CONEXION DEL CLIENTE");
        sock = new Sockets("localhost", 5000);
        recibirObjeto();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServidorActionPerformed
        System.out.println("SOLICITUD DE LA CONEXION DEL SERVIDOR");
        sock = new Sockets(5000);
        recibirObjeto();
    }//GEN-LAST:event_btnServidorActionPerformed

    public void agregar() {

        for (int i = 0; i < ajedrez.getFilas(); i++) {
            for (int j = 0; j < ajedrez.getColumnas(); j++) {
                this.matrizGrafica[i][j] = new VistaFicha(ajedrez.getAreaJuego()[i][j]);
                matrizGrafica[i][j].addMouseListener(this);
                panelAreaJuego.add(getMatrizGrafica()[i][j]);
            }
        }
    }

    public void actualizar() {
        panelAreaJuego.removeAll();
        agregar();
        revalidate();
    }

    public void recibirObjeto() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    ajedrez = sock.recibir();
                    actualizar();
                }
            }
        }).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAreaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAreaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAreaJuego;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {

        int contador = 0;
        for (int i = 0; i < ajedrez.getAreaJuego().length; i++) {
            for (int j = 0; j < ajedrez.getAreaJuego()[0].length; j++) {

                if (e.getSource() == panelAreaJuego.getComponent(contador++)) {

                    if (!ajedrez.getAreaJuego()[i][j].getPuedeSerComida()) {
                        ajedrez.anularFichasMarcadas();
                        ajedrez.anularFichasPuedenSerComidas();

                        ajedrez.getAreaJuego()[i][j].setFichaMarcada(true);
                        ajedrez.setAtacante(ajedrez.getAreaJuego()[i][j]);
                        ajedrez.movimientos();

                    } else if (ajedrez.getAreaJuego()[i][j].getPuedeSerComida()) {
                        ajedrez.cambioFichas(ajedrez.getAreaJuego()[i][j]);
                        actualizar();
                        sock.enviar(ajedrez);

                        if (ajedrez.jaqueMate()) {
                            JOptionPane.showMessageDialog(null, "Jugador #" + ajedrez.getJugadorGanador() + " ha ganado");
                        }

                    }
                }
            }
        }

        actualizar();
    }

    @Override
    public void mousePressed(MouseEvent e
    ) {
    }

    @Override
    public void mouseReleased(MouseEvent e
    ) {
    }

    @Override
    public void mouseEntered(MouseEvent e
    ) {

    }

    @Override
    public void mouseExited(MouseEvent e
    ) {
    }
}
